name: Verify

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  verify:
    name: Verify

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        node-version: [ 20.x, 22.x ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v7

    - name: Setup Node
      uses: actions/setup-node@v7
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      uses: bahmutov/npm-install@v1

    - name: Check code style
      run: npm run codestyle

    - name: Run tests
      run: npm run test
