name: Verify

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  verify:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        node-version: [ 18.x, 20.x, 22.x ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      uses: bahmutov/npm-install@v1

    - name: Run linter
      run: npm run lint

    - name: Run tests
      run: npm run test
